### ISSUE TITLE
Unified multiple value reponse

### ISSUE THREAD

**Issue by zankia** [remyla/damas-core#114]
### Setup

According to old tests : if the specified id is not found, the operation must send a 404 error whereas this error is not sent anymore.
Indeed, if the operation returns an array, it fills the response by as much `null` as not found ids and sends a 200 success.
The problem is that clients don't know if an error occurred or not.
The other problematic is "_do we have to continue the process if an error occurred ?_"
### Solution proposed

A good way to fix it could be processing over all elements of the array parameter and send : 
- As much `null` as errors
- 200 (or 201) if all succeeded
- 207 if some succeeded and some didn't
- 404 if no ids were found at all

**Comment by remyla** [comment]
thank you very much

so if I understand well, we will improve the quality of the results sent by the operations of the web service: more consistent result bodies and status codes were multiple input are processed.

The HTTP status code 207 corresponds to the message "Multi-Status", which is appropriate when processing multiple input.

This is related to #106 since we will have to update the description of the returned status codes.

Which operations are involved? it would be good to have the list of the affected operations.

**Comment by zankia** [comment]
Every operation offering multiple ids as input is involved : 
* Create
* Read
* Update
* Graph

Delete could be also involved (by returning an array) but the model doesn't seem to send a response for every input, it sends a response for the whole operation.

**Comment by remyla** [comment]
Do you think that it is preferable to take care of the Delete operation at the same time for consistency, or to change its specification during a second step?

**Comment by zankia** [comment]
We can make Delete send the right HTTP status code (207 for both deleted and errors) in a first step and leave return value homogenization for later

**Comment by remyla** [comment]
When I see the server implementation of the delete operation, what happens if one of the elements could not be deleted?

```js
    /**
     * Delete specified nodes.
     * @param {array} ids - List of node ids to delete
     * @param {function} callback - Callback function to routes.js
     */
    self.remove = function (ids, callback) {
        self.getCollection(callback, function (coll) {
            var ids_o = exportIds(ids);
            coll.remove({'_id': {$in: ids_o}}, function (err, result) {
                if (err || result.result.n === 0) {
                    callback(true);
                    return;
                }
                callback(false, result);
            });
        });
    }; // remove()
```


When I have a look at the client implementation of the delete method, I see that it returns a boolean anyway. Having a 207 will make it return false, as it is different from 200


```py
r = requests.delete(self.serverURL+'/delete/'+id_, headers=self.headers, verify=False)
return r.status_code == 200
```

```js
return req.status === 200
```

So depending on the server current behavior, could we go further and make the delete handle consistent result too (arrays when multi delete)?
