### ISSUE TITLE
socket.io implementation

### ISSUE THREAD

**Issue by remyla** [remyla/damas-core#18]
## [nodejs, js] socket.io

GOAL: provide a socket.io message layer into damas-core, in server-nodejs and a separate js client, with all our features of our REST API

@jogal360 @Baenshee @MatLala @remyla

**Comment by gnoxr** [comment]
`socket.io` is a module providing a simple way to provide a WebSocket client or server.

Import `socket.io` and assign it the existing servers :

```javascript
var io = require('socket.io')();
io.attach(http);
io.attach(https);
```

How to use the API (server-side) :

```javascript
// Global variable accessible for all sockets *concurrently*
var total_users = 0;

io.on('connection', function(socket) {
    // Local variable for the current connection (until the socket closes)
    var local_clicks = 0;
    // Variable stored in the socket session
    socket.user_id = ++total_users;
    socket.on('message', function (obj) { // Receive the message 'message'
        socket.emit('reception', obj); // Send back the object the client sent
        socket.broadcast.emit('reception', obj); // Send the object to every connected client
    });
});
```

The client-side principle is the same (without the broadcast socket) :

```javascript
var socket = io();
socket.on('reception', function (obj) {
    alert(obj.author + ' said: ' + obj.content);
});
socket.emit('message', {content: "hello world"});
```

**Comment by gnoxr** [comment]
Using WebSockets, we can only send one object per "request", and we listen for very specific messages.

It is a problem for the `update` method, as we expect to have the ids in the URI and the content in the request body. We don't have the URI. What should we do?

Note that this decision might impact more than just the `update` method.

### 1. Compound object

- Similar to our current HTTP implementation
- No content duplication

```json
{
    'ids': [id1, id2, ...],
    'content': {'key': 'value'}
}
```

### 2. Specific updates

- More precise
- Looks more like what we should have in a mongo-independant system?

```json
{
    'id1': {'key': 'value'},
    'id2': {'key': 'value'},
    'id3': {'key': 'value'}
}
```

**Comment by remyla** [comment]
for the specific updates you describe, I would put the ids in the objects directly.

Do you think that these specific updates could make the update operator more consistent than the current one?

**Comment by gnoxr** [comment]
We usually refer to something by its name, not by something containing its name.

For Mongo, identifiers are "inside" of objects, but with other DBMS, the ids are "outside". With Redis, an object exists at a known reference - its id. With the MySQL tables of damas-core, the id is also stored in a separated table (if I remember well).

I think this is a more logical behavior.

However, we might want to apply the same operations on multiple elements. In this case, the "compound object", providing separately a list of ids and the new content for all elements, is a far better solution (and is compatible with our current implementations), although we need multiple requests when we want to update differently multiple objects.

**Comment by gnoxr** [comment]
Agreed solution: we do not need to implement the REST API via the websockets, as the routes already do so. Instead, we use the websockets in order to allow the connected clients to listen for changes and to apply them locally, as they can use HTTP to perform requests.

This way we have almost nothing to change in existing code, and we keep the codebase cleaner.

**Comment by gnoxr** [comment]
There were still problems with `socket.io`, because of my use of self-signed certificates for local working. I tried both `ws` directly and `socket.io` before finding solutions, which were undocumented as the problem came from dependencies which did not produce debugging data. Here is my report:

### ws

- Only supports websockets (no fallback protocol)
- No automatic reconnection
- No debug messages (does not use the `debug` module)
- No message encapsulation (harder to work with, we have to encode and decode objects and emulate the event system)
- Is the fastest websocket library for node.js

### socket.io

- Supports multiple fallback protocols (however, only the polling is enabled by default)
- Performs automatic reconnection and stores undelivered packets to send them when possible
- Lots of not-so-useful (it didn't help solving problems) and very verbose debugging (avoid using `DEBUG=*`)
- Encapsulates messages (way easier to work with)
- Uses ws as a backend (but with lots of encapsulations)

### Self-signed certificates

When using self-signed certificates (ex. generated using openssh), there are a few changes we have to make in order to have the program working :
- ws:
  - node client: set the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0`
  - browser: untested
- socket.io: set the option `rejectUnauthorized: false` in the client options
